### PR TITLE
Added SENAITE LIMS/LIS. Bika endorses SENAITE

### PR DESCRIPTION
**Pull request by xispa**
SENAITE is an Open Source LIMS for enterprise environments. It is especially focused on high speed, excellent performance and stability. It currently ships with an integrated JSON API, has a user friendly GUI and provides rich UI components. It is a derivative work of Bika LIMS software, built on top of Plone CMS with Python as its main programming language. There have been many architectural changes with respect to its predecessor Bika LIMS.

The heart of SENAITE is [SENAITE CORE](https://github.com/senaite/senaite.core), which provides the base functionalities of a mature and secure LIMS. The way to interact with SENAITE CORE is [SENAITE LIMS](https://github.com/senaite/senaite.lims). Its predecessor Bika LIMS depends heavily on JavaScript, and most of the logic is custom built with jQuery. While this is applicable for smaller projects, it is almost impossible to maintain in larger projects. Therefore, SENAITE LIMS introduces modern JavaScript frameworks like ReactJS, BackboneJS or AngularJS to provide a robust user interface which follows industry standards. Last but not least, SENAITE LIMS follows a mobile first approach and is built with Twitter Bootstrap. This makes it possible and easy to operate in the web interface with tablets and smart devices.

SENAITE also ships with a complete RESTful JSON API built on plone.jsonapi.routes, which serves as the main communication interface between SENAITE CORE and any kind of modern web framework. This makes great web applications like the Spotlight Search or the Plone Commander possible and allows frontend developers to interface custom web application with SENAITE CORE.

**Additional resources**

- [Bika Collective announcement about the endorsement of SENAITE](https://www.bikalims.org/news/Bika_LIMS_death_premature)
- [SENAITE.CORE on Github](https://github.com/senaite/senaite.core)
- [SENAITE.HEALTH on Github](https://github.com/senaite/senaite.health)
- [SENAITE software family in project's page on GitHub](https://github.com/senaite)
- [SENAITE on Pypi](https://pypi.python.org/pypi?%3Aaction=search&term=senaite&submit=search)
- [Gitter chatroom](https://gitter.im/senaite-lims/Lobby)
- [Community forum (Discourse)](https://community.senaite.org)
- [Users list](https://sourceforge.net/projects/senaite/lists/senaite-users)
- [Official website](http://www.senaite.com/)

### CODE REVIEW

**Comment by MatthewVita** [comment]
@xispa,

Wow! I didn't see the update that Bika development stopped.

Would you say that Senaite is operational/functional at this early stage?

Thanks,
Matthew Vita

**Comment by xispa** [comment]
Hi @MatthewVita we know of some labs that are using SENAITE in production environments already. Also, as per some feedback received through Gitter channel and emails in private, there are some that are in a pre-production phase within the migration process from Bika to SENAITE. Some are upgrading from Bika followiing the traditional stepped upgrade procedure, while others make use of [`senaite.sync`](https://github.com/senaite/senaite.sync), an add-on, that precisely allows the migration of data from old instances to Senaite.

I wouldn't say SENAITE is in an early stage, rather `senaite.core` has been built reusing most of the code of Bika, but with some new features, architectural changes for better performance and bugfixes. Although most of the transition from Bika to SENAITE took place during the last quarter of 2017, a lot of architectural refactoring was done since May 2017 in a separate fork. As a result of all these efforts, the first SENAITE release was published in January 2018.

**Comment by MatthewVita** [comment]
Hi @xispa,

Thanks for the clarifying information. I also see that the Bika website points to SENAITE, which gives me confidence that using the word "superseded" is appropriate next to the Bika entry.

Wanted to make sure I was up to date because forks can sometimes be political where a fork's leaderships paints the origin project as a defunct project, even if it's not.

Anyways, can you enhance the descriptor in your PR? "Professional, open source LIMS/LIS software" - you can drop the word "Professional", "open source" is redundant so you can remove that.

**Comment by MatthewVita** [comment]
Thanks for amending, Jordi.

Looking forward to great success in the future of Bika!

**Pull request merged**
