### PR TITLE
Copy review on README.md

### PR DESCRIPTION
**Pull request by ioreka**
Very light copy changes to ensure consistency and catch a couple of spelling mistakes.

### CODE REVIEW

**Review by sroze — APPROVED** [review]
Looks great to me 😍

**Comment by programmers** [comment]
Looks great! I'm glad you tackled the weak spots (and more).

My review comments:

1. "Tomography [...] aimed at both scientists and lay people." is an improvement but it looks a tad awkward to me. Can we just say "for both"?

2. I can't believe we had "HIPPA" instead of "HIPAA". How embarrassing... :)

**Comment by MatthewVita** [comment]
Looks great! I'm glad you tackled the weak spots (and more).

"Tomography [...] aimed at both scientists and lay people." is an improvement but it looks a tad awkward to me. Can we just say "for both"?

I can't believe we had "HIPPA" instead of "HIPAA". How embarrassing... :)

**Comment by ioreka** [comment]
I incorporated your suggestion, thanks for catching! HIPPA made me giggle, like patient data privacy for semi-aquatic mammals. 

I'd like to change the phrasing throughout for consistency - some entries are structured with a pronoun ("X is a [description of technology] for [more explanation]" and some skip straight to indefinite article ("A [description of technology] for [more explanation]"). It's a small thing, but I spend a lot of time reviewing copy like this so it sticks out to me. Are you happy for me to standardize and if so, a preference for style? @MatthewVita

**Comment by programmers** [comment]
Awesome, thanks for that change, @ioreka,

I agree we have inconsistencies with phrasing. Which of the two do you prefer to apply?

While we're cleaning things up, I'm interested in your take on how to handle "generic" entries like this:

`FHIR - Fast Health Interoperability Resources.`
`Horos - Medical image viewer.`
`DCMTK - DICOM Toolkit.`

These are all non-descriptive entries, but sometimes they speak for themselves. Everyone knows what FHIR is, for instance. Not sure if it's worth it to add some light descriptions to all like this. Thoughts? Do you think this should this be another Github issue for us to brainstorm about?

**Comment by MatthewVita** [comment]
Awesome, thanks for that change, @ioreka,

I agree we have inconsistencies with phrasing. Which of the two do you prefer to apply?

While we're cleaning things up, I'm interested in your take on how to handle "generic" entries like this:

`FHIR - Fast Health Interoperability Resources.`
`Horos - Medical image viewer.`
`DCMTK - DICOM Toolkit.`

These are all non-descriptive entries, but sometimes they speak for themselves. Everyone knows what FHIR is, for instance. Not sure if it's worth it to add some light descriptions to all like these. Thoughts? Do you think this should this be another Github issue for us to brainstorm about?

**Comment by ioreka** [comment]
@MatthewVita I've picked a style to use consistently, it's the simplest for brevity. 

Agreed it might be good to add a line for things like FHIR - helps with accessibility and doesn't assume pre-requisite knowledge. 

A couple of the descriptions are a little "marketing" and not objectively descriptive (I guess some people missed the line in the readme about avoiding superlatives like "the best" etc!) so if you are on board I can open an issue with some suggestions? I'm happy to take the time to check through all the links to ensure the brief descriptions are up to date and clear for new users.

**Comment by MatthewVita** [comment]
@ioreka I think your writing/organizational style is wonderful. Speaking of that, can I merge this PR? Any last minute changes?

Please do open up issues regarding the resources that read more like marketing materials (or show some bias). I'm looking forward to your ideas. Great stuff.

**Comment by ioreka** [comment]
Yes please do merge @MatthewVita!! My apologies for the delay. Got some free time next week and have pencilled in reviewing this README. Looking forward to it!

**Pull request merged**
