### PR TITLE
Added Atlas tools for healthcare.

### PR DESCRIPTION
**Pull request by christopherpickering**

### CODE REVIEW

**Comment by kakoni** [comment]
Hi @christopherpickering ! [Atlas BI Library] seems useful! Could you move that under ### Data category and I'll merge the request.

**Comment by christopherpickering** [comment]
thanks! Should be good.

**Review by kakoni — APPROVED** [review]
Changed order a bit + removed sftp tool for now.

**Comment by kakoni** [comment]
Thank you for adding this interesting library!

**Comment by christopherpickering** [comment]
Thanks!

**Pull request merged**
